imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

    - { resource: @BDNStoreBundle/Resources/config/main.yml }

    - { resource: @BDNBotBundle/Resources/config/main.yml }
    - { resource: @BDNBotBundle/Resources/config/parameters.yml }

    - { resource: @BDNUserBundle/Resources/config/main.yml }
    - { resource: @BDNUserBundle/Resources/config/parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_default_host%"
                port:     "%database_default_port%"
                dbname:   "%database_default_name%"
                user:     "%database_default_user%"
                password: "%database_default_password%"
                charset:  UTF8
            community:
                driver:   pdo_mysql
                host:     "%database_community_host%"
                port:     "%database_community_port%"
                dbname:   "%database_community_name%"
                user:     "%database_community_user%"
                password: "%database_community_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

d_zunke_slack:
    token: "%slack_token%"
    identities:
        BDN:
          icon_url: http://station.ketelaar.me/files/unnamed60.png

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

nelmio_api_doc:
    name: BDN API V3
    cache:
        enabled: true

hwi_oauth:
    http_client:
        timeout:       10
        verify_peer:   false
        ignore_errors: false
        max_redirects: 5
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            forums: forums
    connect:
        confirmation: true
    resource_owners:
        forums:
            type: oauth2
            client_id: '%oauth_id%'
            client_secret: '%oauth_secret%'
            access_token_url: https://www.parabot.org/community/applications/oauth2server/interface/oauth/token.php
            authorization_url: https://www.parabot.org/community/applications/oauth2server/interface/oauth/authorize.php
            infos_url: https://www.parabot.org/community/applications/oauth2server/interface/oauth/me.php
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            options:
                use_bearer_authorization: false
            paths:
                identifier: id
                nickname: username
                realname: fullname
                email: email
            scope: user.profile user.email user.groups

doctrine_migrations:
    dir_name: "%kernel.root_dir%/Migrations"
    namespace: BDN\Migrations
    table_name: migration_versions
    name: BDN Migrations