app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "../../src/Parabot/BDN/UserBundle/Resources/config/routing.yml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

_security_check:
    path:  /login_check
_security_logout:
    path:  /logout
_security_login:
    path:  /login
