bdn_community:
    resource: "@BDNCommunityBundle/Controller/"
    type:     annotation
    prefix:   /

bdn_store:
    resource: "@BDNStoreBundle/Controller/"
    type:     annotation
    prefix:   /api/store

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:home }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api/users

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /api/users

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /api/group

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security_check:
    pattern: /api/users/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_login:
    pattern: /api/users/login
    defaults: { _controller: FOSUserBundle:Security:login }
    requirements:
        _method: GET|POST

fos_user_resetting_reset:
    pattern: /api/users/logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    requirements:
        _method: GET|POST