bdn_bot:
    resource: "@BDNBotBundle/Controller/BotController.php"
    type:     annotation
    prefix:   /api/bot

bdn_bot_translations:
    resource: "@BDNBotBundle/Controller/TranslationController.php"
    type:     annotation
    prefix:   /api/bot/translations

bdn_servers:
    resource: "@BDNBotBundle/Controller/ServerController.php"
    type:     annotation
    prefix:   /api/servers

bdn_script:
    resource: "@BDNBotBundle/Controller/ScriptController.php"
    type:     annotation
    prefix:   /api/scripts

bdn_script_reviews:
    resource: "@BDNBotBundle/Controller/Scripts/ReviewController.php"
    type:     annotation
    prefix:   /api/scripts/reviews

bdn_bot_libraries:
    resource: "@BDNBotBundle/Controller/Bot/LibraryController.php"
    type:     annotation
    prefix:   /api/bot/libraries

bdn_bot_notifications:
    resource: "@BDNBotBundle/Controller/Bot/SlackNotificationController.php"
    type:     annotation
    prefix:   /api/bot/notifications/slack

bdn_signatures:
    resource: "@BDNBotBundle/Controller/SignatureController.php"
    type:     annotation
    prefix:   /api/signatures

bdn_teamcity:
    resource: "@BDNBotBundle/Controller/TeamCityController.php"
    type:     annotation
    prefix:   /api/city

bdn_store:
    resource: "@BDNStoreBundle/Controller/"
    type:     annotation
    prefix:   /api/store

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:home }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /

bdn_oauth_server:
    resource: "@BDNOAuthServerBundle/Resources/config/routing.yml"
    prefix:   /api/users/oauth/v2

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    prefix: /

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    prefix: /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api/users

user:
    resource: "@BDNUserBundle/Resources/config/routing.yml"
    prefix: /api/users

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /api/group

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /api/users/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /api/users/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /api/users/connect

hwi_forums_login:
    pattern: /api/users/login/forums

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc