app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /api

user:
    resource: "../../src/Parabot/BDN/UserBundle/Resources/config/routing.yml"
    prefix: /api/users

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api/users

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /api/group

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"