app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api/users

user:
    resource: "../../src/Parabot/BDN/UserBundle/Resources/config/routing.yml"
    prefix: /api/users

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /api/group

_security_check:
    path:  /login_check
_security_logout:
    path:  /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /api/users