bdn_bot:
    resource: "@BDNBotBundle/Controller/BotController.php"
    type:     annotation
    prefix:   /api/bot

bdn_bot_translations:
    resource: "@BDNBotBundle/Controller/TranslationController.php"
    type:     annotation
    prefix:   /api/bot/translations

bdn_script:
    resource: "@BDNBotBundle/Controller/ScriptController.php"
    type:     annotation
    prefix:   /api/scripts

bdn_store:
    resource: "@BDNStoreBundle/Controller/"
    type:     annotation
    prefix:   /api/store

home:
    path:      /
    defaults:  { _controller: AppBundle:Default:home }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /asd

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /api/users

user:
    resource: "@BDNUserBundle/Resources/config/routing.yml"
    prefix: /api/users

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /api/group

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /api/users/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /api/users/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /api/users/connect

hwi_forums_login:
    pattern: /api/users/login/forums