# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_DEVELOPER:   ROLE_USER
        ROLE_ADMIN:       ROLE_DEVELOPER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            logout:       true
            anonymous:    true

        login:
            pattern: ^/api/users/login$
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: fos_user_security_check
                default_target_path: /
                always_use_default_target_path: true
                failure_path: /api/users/login
                login_path: /api/users/login
                failure_handler: authentication_handler
                success_handler: authentication_handler

            anonymous: true
            logout: true

    access_control:
        - { path: ^/api/users/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/scripts/admin/, role: ROLE_SCRIPTER }
        - { path: ^/scripts/, role: ROLE_USER }

    access_denied_url: unauthorised_notice