security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            entry_point: entry_point_authorisation
            oauth:
                resource_owners:
                    forums: /connect/check-forums
                login_path: /connect/check-forums
                failure_path: /user/login
                default_target_path: /api/users/loggedin
                oauth_user_provider:
                    service: oauth_user_provider
                remember_me: true
            anonymous: true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }