imports:
    - { resource: @BDNStoreBundle/Resources/config/services.yml }
    - { resource: @BDNUserBundle/Resources/config/services.yml }
    - { resource: @BDNBotBundle/Resources/config/services.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    slack_manager:
        class: AppBundle\Service\SlackManager
        arguments: ['@dz.slack.messaging', '@dz.slack.identity_bag']