imports:
    - { resource: @BDNStoreBundle/Resources/config/services.yml }
    - { resource: @BDNUserBundle/Resources/config/services.yml }
    - { resource: @BDNBotBundle/Resources/config/services.yml }

parameters:
#    parameter_name: value

services:
    slack_manager:
        class: AppBundle\Service\SlackManager
        arguments: ['@dz.slack.messaging', '@dz.slack.identity_bag']
    date_time.normalizer:
        class: AppBundle\Service\Normalizers\DateTimeNormalizer
        tags:
            -  { name: serializer.normalizer }