<?php

namespace Parabot\BDN\CommunityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommunityUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityUserRepository extends EntityRepository
{
}
