services:
    bot.type_listener:
        class: Parabot\BDN\BotBundle\Listener\TypeListener
        arguments:
            - @kernel
        tags:
            - { name: doctrine.event_listener, event: postLoad }
#    s3:
#        key: "%aws_key%"
#        secret: "%aws_key%"
#        region: us-west-1