parameters:
  sylius.model.sequence.class: Sylius\Component\Sequence\Model\Sequence

services:
  app.order_number_listener:
    class: Sylius\Bundle\OrderBundle\EventListener\OrderNumberListener
    arguments:
      - "@sylius.sequence.doctrine_number_listener"
    tags:
      - { name: kernel.event_listener, event: app.script_ordered, method: generateOrderNumber }