<?php

namespace Parabot\BDN\BotBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Parabot\BDN\BotBundle\Entity\Servers\Hook;
use Parabot\BDN\BotBundle\Entity\Servers\Server;

/**
 * HookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HookRepository extends EntityRepository {

    /**
     * @param Server $server
     *
     * @return Hook[]
     */
    public function findHooksByServer(Server $server){
        $query = $this->getEntityManager()->createQuery(
            'SELECT s FROM BDNBotBundle:Servers\Hook s JOIN s.server a WHERE a.id = :id'
        )->setParameter('id', $server->getId());

        return $query->getResult();
    }
}
