<?php

namespace Parabot\BDN\BotBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScriptRepository extends EntityRepository
{
}
