<?php

namespace Parabot\BDN\BotBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Parabot\BDN\BotBundle\Entity\Servers\Server;
use Parabot\BDN\BotBundle\Entity\Servers\ServerSlackChannel;

/**
 * ServerSlackChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerSlackChannelRepository extends EntityRepository {
    /**
     * @param $id
     *
     * @return Server
     */
    public function findById($id) {
        /**
         * @var Server|null $server
         */
        $server = $this->findOneBy([ 'id' => $id ]);

        return $server;
    }

    /**
     * @param Server $server
     *
     * @return ServerSlackChannel[]
     */
    public function findByServer($server) {
        $query = $this->getEntityManager()->createQuery(
            'SELECT s FROM BDNBotBundle:Servers/ServerSlackChannel s JOIN s.server a WHERE a.id = :id'
        )->setParameter('id', $server->getId());

        return $query->getResult();
    }
}