fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Parabot\BDN\UserBundle\Entity\User
    group:
        group_class: Parabot\BDN\UserBundle\Entity\Group

scheb_two_factor:
    google:
        enabled: true
        template: AppBundle:Authentication:form.html.twig
    trusted_computer:
        enabled: true
        cookie_name: two_factor_trusted_computer
        cookie_lifetime: 5184000 # 60 days

fos_rest:
    routing_loader:
        default_format: json                            # All responses should be JSON formated
        include_format: false                           # We do not include format in request, so that all responses

fos_oauth_server:
    db_driver:           orm
    client_class:        Parabot\BDN\UserBundle\Entity\OAuth\Client
    access_token_class:  Parabot\BDN\UserBundle\Entity\OAuth\AccessToken
    refresh_token_class: Parabot\BDN\UserBundle\Entity\OAuth\RefreshToken
    auth_code_class:     Parabot\BDN\UserBundle\Entity\OAuth\AuthCode
    service:
        user_provider: fos_user.user_manager             # This property will be used when valid credentials are given to load the user upon access token creation

jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false

    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: true

    # Allows you to disable some, or all built-in voters
    voters:
        disable_authenticated: false
        disable_role:          false
        disable_acl:           false

    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control: { }

    util:
        secure_random:
            connection: default
            table_name: seed_table