services:
    community.connector:
        class:  Parabot\BDN\CommunityBundle\Service\Connector
        calls:
          - [setContainer, [@service_container]]
          - [setInformation]

    authentication_handler:
        class: Parabot\BDN\UserBundle\Listener\AuthenticationListener