services:
    authentication_handler:
        class: Parabot\BDN\UserBundle\Listener\AuthenticationListener
        arguments: ['@doctrine.orm.entity_manager']

    api_key_user_provider:
        class: Parabot\BDN\UserBundle\Provider\ApiKeyUserProvider
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    apikey_authenticator:
        class:  Parabot\BDN\UserBundle\Listener\ApiKeyAuthenticator
        public: false

    bdn_authenticator:
        class:     Parabot\BDN\UserBundle\Security\BDNAuthenticator
        arguments: ["@security.password_encoder"]

    bdn_connector:
        class:    Parabot\BDN\UserBundle\Service\Connector
        arguments: ['@doctrine.dbal.community_connection', '@doctrine.orm.entity_manager', '@security.password_encoder']

    bdn_blocking_login_listener:
        class: Parabot\BDN\UserBundle\Listener\BlockingLoginListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9 }
        arguments: [%blocking_routes%, '@doctrine.orm.entity_manager', %block_count%]