services:
    authentication_handler:
        class: Parabot\BDN\UserBundle\Listener\AuthenticationListener

    api_key_user_provider:
        class: Parabot\BDN\UserBundle\Provider\ApiKeyUserProvider

    apikey_authenticator:
        class:  Parabot\BDN\UserBundle\Listener\ApiKeyAuthenticator
        public: false