services:
    authentication_handler:
        class: Parabot\BDN\UserBundle\Listener\AuthenticationListener

    api_key_user_provider:
        class: Parabot\BDN\UserBundle\Provider\ApiKeyUserProvider
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    apikey_authenticator:
        class:  Parabot\BDN\UserBundle\Listener\ApiKeyAuthenticator
        public: false

    bdn_authenticator:
        class:     Parabot\BDN\UserBundle\Security\BDNAuthenticator
        arguments: ["@security.password_encoder"]