<?php

namespace AppBundle\Entity;

/**
 * PBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PBRepository extends \Doctrine\ORM\EntityRepository {
}
